spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    platform: postgres
    hikari:
      connection-test-query: SELECT 1

  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate

  flyway:
    baselineOnMigrate: true
    validateOnMigrate: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher